(()=>{"use strict";
const $=x=>document.getElementById(x),cfg=window.RETRO_CONFIG||{};
const live=/^https:\/\/[a-z0-9-]+\.supabase\.co$/i.test(cfg.SUPABASE_URL||"")&&/^(sb_publishable_|eyJ)/.test(cfg.SUPABASE_PUBLISHABLE_KEY||"");
const sb=live&&window.supabase?window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_PUBLISHABLE_KEY):null;
let cid=localStorage.getItem("retro_client_id");if(!cid){cid=(crypto.randomUUID?crypto.randomUUID():Date.now()+"-"+Math.random());localStorage.setItem("retro_client_id",cid)}
let room=null,me=null,thoughts=[],reactions=[],people=[],section=null,ch=null;
let d={rooms:JSON.parse(localStorage.getItem("rr_rooms")||"{}"),thoughts:JSON.parse(localStorage.getItem("rr_thoughts")||"[]"),reactions:JSON.parse(localStorage.getItem("rr_reactions")||"[]"),people:JSON.parse(localStorage.getItem("rr_people")||"[]")};
const persist=()=>localStorage.setItem("rr_rooms",JSON.stringify(d.rooms))||localStorage.setItem("rr_thoughts",JSON.stringify(d.thoughts))||localStorage.setItem("rr_reactions",JSON.stringify(d.reactions))||localStorage.setItem("rr_people",JSON.stringify(d.people));
function err(m){$("err").textContent=m;$("err").style.display=m?"block":"none"}function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function code(){return Math.random().toString(36).slice(2,8).toUpperCase()}function setup(join){$("setup").classList.remove("hidden");$("board").classList.add("hidden");$("create").classList.toggle("hidden",join);$("join").classList.toggle("hidden",!join);$("ct").classList.toggle("active",!join);$("jt").classList.toggle("active",join);$("start").textContent=join?"Join room":"Create room";$("pill").textContent=sb?"Live mode":"Demo mode"}
async function create(){const n=$("rname").value.trim(),u=$("cname").value.trim();if(!n||!u)return err("Enter a room name and your name.");let c=code();if(sb){for(let i=0;i<5;i++){const q=await sb.from("rooms").select("id").eq("code",c).maybeSingle();if(q.error)return err(q.error.message);if(!q.data)break;c=code()}const q=await sb.from("rooms").insert({code:c,name:n}).select().single();if(q.error)return err(q.error.message);room=q.data}else{while(d.rooms[c])c=code();room={id:crypto.randomUUID?crypto.randomUUID():Date.now()+"",code:c,name:n,created_at:new Date().toISOString()};d.rooms[c]=room;persist()}await join(u)}
async function joinByCode(){const c=$("rcode").value.trim().toUpperCase(),u=$("jname").value.trim();if(!/^[A-Z0-9]{6}$/.test(c))return err("Enter a valid 6-character room code.");if(!u)return err("Enter your name.");let r;if(sb){const q=await sb.from("rooms").select("*").eq("code",c).maybeSingle();if(q.error)return err(q.error.message);r=q.data}else r=d.rooms[c];if(!r)return err("Room not found. Check the code.");room=r;await join(u)}
async function join(u){if(sb){const q=await sb.from("participants").upsert({room_id:room.id,name:u,client_id:cid},{onConflict:"room_id,client_id"}).select().single();if(q.error)return err(q.error.message);me=q.data}else{me=d.people.find(x=>x.room_id===room.id&&x.client_id===cid);if(!me){me={id:crypto.randomUUID?crypto.randomUUID():Date.now()+"",room_id:room.id,name:u,client_id:cid,joined_at:new Date().toISOString()};d.people.push(me)}else me.name=u;persist()}history.replaceState(null,"","#room="+room.code);$("setup").classList.add("hidden");$("board").classList.remove("hidden");$("title").textContent=room.name;$("room").textContent="Room "+room.code;$("pill").textContent=sb?"Live":"Demo";await refresh();if(sb)subscribe()}
async function refresh(){if(sb){const [a,b,c]=await Promise.all([sb.from("thoughts").select("*").eq("room_id",room.id).order("created_at",{ascending:true}),sb.from("reactions").select("*"),sb.from("participants").select("*").eq("room_id",room.id).order("joined_at",{ascending:true})]);thoughts=a.data||[];reactions=(b.data||[]).filter(r=>thoughts.some(t=>t.id===r.thought_id));people=c.data||[]}else{thoughts=d.thoughts.filter(t=>t.room_id===room.id);reactions=d.reactions.filter(r=>thoughts.some(t=>t.id===r.thought_id));people=d.people.filter(p=>p.room_id===room.id)}render()}
function render(){const g={good:[],problem:[],shout:[]};thoughts.forEach(t=>g[t.section].push(t));[["good","gl","gc"],["problem","pl","pc"],["shout","sl","sc"]].forEach(([s,l,c])=>{$(c).textContent=g[s].length;$(l).innerHTML=g[s].length?g[s].map(card).join(""):'<div class="empty">No thoughts yet.</div>'});$("people").textContent=people.length+(people.length===1?" participant":" participants")}
function card(t){const ct=x=>reactions.filter(r=>r.thought_id===t.id&&r.reaction_type===x).length;return `<article class="thought"><p>${esc(t.content)}</p><div class="meta">By ${esc(t.author_name)}${t.section==="shout"&&t.recipient_name?" · Shout-out to "+esc(t.recipient_name):""}</div><div class="reactions"><button class="reaction" data-id="${t.id}" data-r="like">👍 ${ct("like")}</button><button class="reaction" data-id="${t.id}" data-r="heart">❤️ ${ct("heart")}</button><button class="reaction" data-id="${t.id}" data-r="support">👏 ${ct("support")}</button></div></article>`}
function open(s){section=s;$("mt").textContent=s==="shout"?"Add shout-out":"Add thought";$("rw").classList.toggle("hidden",s!=="shout");$("text").value="";$("recipient").value="";$("me").style.display="none";$("mb").classList.remove("hidden");$("text").focus()}function close(){$("mb").classList.add("hidden")}
async function save(){const text=$("text").value.trim(),rec=$("recipient").value.trim();if(!text){$("me").textContent="Enter a thought.";$("me").style.display="block";return}if(section==="shout"&&!rec){$("me").textContent="Enter the colleague's name.";$("me").style.display="block";return}if(sb){const q=await sb.from("thoughts").insert({room_id:room.id,section,content:text,author_name:me.name,recipient_name:section==="shout"?rec:null});if(q.error){$("me").textContent=q.error.message;$("me").style.display="block";return}}else{d.thoughts.push({id:crypto.randomUUID?crypto.randomUUID():Date.now()+"",room_id:room.id,section,content:text,author_name:me.name,recipient_name:section==="shout"?rec:null,created_at:new Date().toISOString()});persist();await refresh()}close()}
async function react(id,type){const x=reactions.find(r=>r.thought_id===id&&r.client_id===cid&&r.reaction_type===type);if(sb){if(x)await sb.from("reactions").delete().eq("id",x.id);else await sb.from("reactions").insert({thought_id:id,client_id:cid,reaction_type:type})}else{if(x)d.reactions=d.reactions.filter(r=>r.id!==x.id);else d.reactions.push({id:crypto.randomUUID?crypto.randomUUID():Date.now()+"",thought_id:id,client_id:cid,reaction_type:type,created_at:new Date().toISOString()});persist();await refresh()}}
function subscribe(){if(ch)sb.removeChannel(ch);ch=sb.channel("retro-"+room.id).on("postgres_changes",{event:"*",schema:"public",table:"thoughts",filter:"room_id=eq."+room.id},refresh).on("postgres_changes",{event:"*",schema:"public",table:"participants",filter:"room_id=eq."+room.id},refresh).on("postgres_changes",{event:"*",schema:"public",table:"reactions"},refresh).subscribe()}
async function share(){const u=location.href;if(navigator.share)try{await navigator.share({title:room.name,text:"Join my retrospective room",url:u});return}catch(e){}try{await navigator.clipboard.writeText(u);alert("Invite link copied.")}catch(e){prompt("Copy this invite link:",u)}}
function exportIt(){const data=thoughts.map(t=>({section:t.section,thought:t.content,author:t.author_name,recipient:t.recipient_name||"",created_at:t.created_at}));const a=document.createElement("a"),b=new Blob([JSON.stringify({room,thoughts:data},null,2)],{type:"application/json"});a.href=URL.createObjectURL(b);a.download="retrospective-"+room.code+".json";a.click();URL.revokeObjectURL(a.href)}
async function leave(){if(!confirm("Leave this retrospective room?"))return;if(sb)await sb.from("participants").delete().eq("id",me.id);else{d.people=d.people.filter(p=>p.id!==me.id);persist()}if(ch)sb.removeChannel(ch);room=me=null;history.replaceState(null,"",location.pathname+location.search);setup(false)}
$("ct").onclick=()=>setup(false);$("jt").onclick=()=>setup(true);$("start").onclick=()=>($("join").classList.contains("hidden")?create():joinByCode());$("cancel").onclick=close;$("save").onclick=save;$("share").onclick=share;$("export").onclick=exportIt;$("leave").onclick=leave;$("mb").onclick=e=>{if(e.target===$("mb"))close()};document.querySelectorAll(".add").forEach(b=>b.onclick=()=>open(b.dataset.s));document.addEventListener("click",e=>{const b=e.target.closest("[data-r]");if(b)react(b.dataset.id,b.dataset.r)});$("rcode").oninput=e=>e.target.value=e.target.value.toUpperCase().replace(/[^A-Z0-9]/g,"").slice(0,6);
const inv=(location.hash.match(/room=([A-Za-z0-9]{6})/)||[])[1];setup(!!inv);if(inv)$("rcode").value=inv.toUpperCase();
})();